apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name:  {{ include "flink.taskmanager.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/part-of: flink
    app.kubernetes.io/component: taskmanager
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.taskmanager.replicaCount }}
  {{- if .Values.taskmanager.updateStrategy }}
  strategy: {{- toYaml .Values.taskmanager.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/part-of: flink
        app.kubernetes.io/component: taskmanager
        {{- if .Values.taskmanager.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.taskmanager.podLabels "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.taskmanager.podAnnotations }}
      annotations:
        {{- if .Values.taskmanager.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.taskmanager.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      {{- if .Values.taskmanager.schedulerName }}
      schedulerName: {{ .Values.taskmanager.schedulerName }}
      {{- end }}
      priorityClassName: {{ .Values.taskmanager.priorityClassName | quote }}
      {{- if .Values.taskmanager.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.taskmanager.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.taskmanager.podAffinityPreset "component" "taskmanager" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.taskmanager.podAntiAffinityPreset "component" "taskmanager" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.taskmanager.nodeAffinityPreset.type "key" .Values.taskmanager.nodeAffinityPreset.key "values" .Values.taskmanager.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.taskmanager.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.taskmanager.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.taskmanager.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.taskmanager.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.taskmanager.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.taskmanager.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.taskmanager.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.taskmanager.topologySpreadConstraints "context" $) | nindent 8 }}
      {{- end }}
      initContainers:
        - name: {{ printf "%s-install-libs-initcontainer" (include "common.names.fullname" .) }}
          image: {{ include "flink.libsJob.image" . }}
          imagePullPolicy: {{ .Values.libs.image.pullPolicy  }}
          command: [ "sh",
                     "-e",
                     "/tmp/scripts/install_libs.sh" ]
          resources: {{- toYaml .Values.libs.resources | nindent 12 }}
          securityContext: {{- .Values.libs.containerSecurityContext | toYaml | nindent 12 }}
          volumeMounts:
            - name: install-libs
              mountPath: /tmp/scripts/
            - name: provisioning
              mountPath: /bitnami/flink-provisioning
              subPath: lib
          {{- if .Values.libs.resources }}
          resources: {{- toYaml .Values.libs.resources | nindent 12 }}
          {{- end }}
      {{- if .Values.taskmanager.initContainers }}
      {{- include "common.tplvalues.render" (dict "value" .Values.taskmanager.initContainers "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: flink-taskmanager
          image: {{ include "flink.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.taskmanager.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.taskmanager.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.taskmanager.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.taskmanager.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.taskmanager.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.taskmanager.args "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.taskmanager.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.taskmanager.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          ports:
            - name: data
              containerPort: {{ .Values.taskmanager.containerPorts.data }}
            - name: ipc
              containerPort: {{ .Values.taskmanager.containerPorts.ipc }}
          env:
            - name: FLINK_MODE
              value: taskmanager
            - name: FLINK_CFG_JOBMANAGER_RPC_ADDRESS
              value: flink-jobmanager-0.flink-headless
            - name: FLINK_CFG_JOBMANAGER_RPC_ADDRESS
              value: flink-jobmanager-0.flink-headless
            - name: FLINK_CFG_HIGH__AVAILABILITY_TYPE
              value: zookeeper
            - name: FLINK_CFG_HIGH__AVAILABILITY_ZOOKEEPER_QUORUM
              value: {{ include "flink.zookeeper.fullAddress" . }}
            - name: FLINK_CFG_HIGH__AVAILABILITY_PATH_ROOT
              value: {{.Values.highAvailability.pathRoot}}
            - name: FLINK_CFG_HIGH__AVAILABILITY_CLUSTER__ID
              value: {{.Values.highAvailability.clusterId}}
            - name: FLINK_CFG_HIGH__AVAILABILITY_STORAGE_DIR
              value: {{ include "flink.minio.uri" . }}
            - name: BITNAMI_DEBUG
              value: {{ ternary "true" "false" .Values.image.debug | quote }}
            {{- if .Values.taskmanager.extraEnvVars }}
              {{- include "common.tplvalues.render" (dict "value" .Values.taskmanager.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: provisioning
              mountPath: /bitnami/flink-provisioning
              subPath: lib
          envFrom:
            {{- if .Values.taskmanager.extraEnvVarsCM }}
            - configMapRef:
                name: {{ .Values.taskmanager.extraEnvVarsCM }}
            {{- end }}
            {{- if .Values.taskmanager.extraEnvVarsSecret }}
            - secretRef:
                name: {{ .Values.taskmanager.extraEnvVarsSecret }}
            {{- end }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.taskmanager.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.taskmanager.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.taskmanager.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.taskmanager.startupProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: web
          {{- end }}
          {{- if .Values.taskmanager.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.taskmanager.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.taskmanager.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.taskmanager.livenessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: web
          {{- end }}
          {{- if .Values.taskmanager.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.taskmanager.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.taskmanager.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.taskmanager.readinessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: web
          {{- end }}
          {{- end }}
          {{- if .Values.taskmanager.resources }}
          resources: {{- toYaml .Values.taskmanager.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.taskmanager.extraVolumeMounts }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.taskmanager.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.taskmanager.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.taskmanager.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        {{- if .Values.libs.install }}
        - name: install-libs
          configMap:
            name: {{ printf "%s-install-libs-configmap" (include "common.names.fullname" .) }}
            items:
              - key: install_libs.sh
                path: install_libs.sh
        - name: provisioning
          emptyDir: { }
        {{- end }}
        {{- if .Values.taskmanager.extraVolumes }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.taskmanager.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
